# frozen_string_literal: true

class BuildsEpisodeWrapper
  def self.call(title:, author:, include_attribution:, content:)
    new(title: title, author: author, include_attribution: include_attribution, content: content).call
  end

  def initialize(title:, author:, include_attribution:, content:)
    @title = title
    @author = author
    @include_attribution = include_attribution
    @content = content
  end

  def call
    "#{intro}\n\n#{@content}\n\n#{outro}"
  end

  private

  def intro
    base = "#{@title}; by #{@author}."
    base += " This audio was generated by PodRead." if @include_attribution
    base
  end

  def outro
    "Thank you for listening to this PodRead generated audio."
  end
end
