# frozen_string_literal: true

class BuildEpisodeWrapper
  def self.call(title:, author:, tier:, content:)
    new(title: title, author: author, tier: tier, content: content).call
  end

  def initialize(title:, author:, tier:, content:)
    @title = title
    @author = author
    @tier = tier.to_s
    @content = content
  end

  def call
    "#{intro}\n\n#{@content}\n\n#{outro}"
  end

  private

  def intro
    base = "#{@title}; by #{@author}."
    base += " This audio was generated by Very Normal TTS." if @tier == "free"
    base
  end

  def outro
    "Thank you for listening to this Very Normal TTS generated audio."
  end
end
