# frozen_string_literal: true

require "test_helper"

class BuildEpisodeWrapperTest < ActiveSupport::TestCase
  test "wraps content with intro and outro for free tier" do
    result = BuildEpisodeWrapper.call(
      title: "Test Article",
      author: "Jane Doe",
      tier: "free",
      content: "This is the article body."
    )

    assert_equal <<~EXPECTED.strip, result
      Test Article; by Jane Doe. This audio was generated by Very Normal TTS.

      This is the article body.

      Thank you for listening to this Very Normal TTS generated audio.
    EXPECTED
  end

  test "wraps content with intro and outro for premium tier" do
    result = BuildEpisodeWrapper.call(
      title: "Test Article",
      author: "Jane Doe",
      tier: "premium",
      content: "This is the article body."
    )

    assert_equal <<~EXPECTED.strip, result
      Test Article; by Jane Doe.

      This is the article body.

      Thank you for listening to this Very Normal TTS generated audio.
    EXPECTED
  end

  test "wraps content with intro and outro for unlimited tier" do
    result = BuildEpisodeWrapper.call(
      title: "Test Article",
      author: "Jane Doe",
      tier: "unlimited",
      content: "This is the article body."
    )

    assert_equal <<~EXPECTED.strip, result
      Test Article; by Jane Doe.

      This is the article body.

      Thank you for listening to this Very Normal TTS generated audio.
    EXPECTED
  end

  test "handles multiline content" do
    content = "First paragraph.\n\nSecond paragraph."

    result = BuildEpisodeWrapper.call(
      title: "Multi Para",
      author: "Author",
      tier: "premium",
      content: content
    )

    assert_includes result, "First paragraph.\n\nSecond paragraph."
    assert result.start_with?("Multi Para; by Author.")
    assert result.end_with?("Thank you for listening to this Very Normal TTS generated audio.")
  end
end
