# frozen_string_literal: true

require "test_helper"

class BuildsEpisodeWrapperTest < ActiveSupport::TestCase
  test "wraps content with intro and outro with attribution for free users" do
    result = BuildsEpisodeWrapper.call(
      title: "Test Article",
      author: "Jane Doe",
      include_attribution: true,
      content: "This is the article body."
    )

    assert_equal <<~EXPECTED.strip, result
      Test Article; by Jane Doe. This audio was generated by PodRead.

      This is the article body.

      Thank you for listening to this PodRead generated audio.
    EXPECTED
  end

  test "wraps content with intro and outro without attribution for premium users" do
    result = BuildsEpisodeWrapper.call(
      title: "Test Article",
      author: "Jane Doe",
      include_attribution: false,
      content: "This is the article body."
    )

    assert_equal <<~EXPECTED.strip, result
      Test Article; by Jane Doe.

      This is the article body.

      Thank you for listening to this PodRead generated audio.
    EXPECTED
  end

  test "handles multiline content" do
    content = "First paragraph.\n\nSecond paragraph."

    result = BuildsEpisodeWrapper.call(
      title: "Multi Para",
      author: "Author",
      include_attribution: false,
      content: content
    )

    assert_includes result, "First paragraph.\n\nSecond paragraph."
    assert result.start_with?("Multi Para; by Author.")
    assert result.end_with?("Thank you for listening to this PodRead generated audio.")
  end
end
