# frozen_string_literal: true

require "test_helper"

class SubmitsEpisodeForProcessingTest < ActiveSupport::TestCase
  include ActiveJob::TestHelper

  setup do
    @episode = episodes(:one)
    @episode.update!(title: "Test Title", author: "Test Author")
    @episode.user.update!(account_type: :standard)
  end

  test "enqueues GeneratesEpisodeAudioJob" do
    assert_enqueued_with(job: GeneratesEpisodeAudioJob, args: [ { episode_id: @episode.id, action_id: nil } ]) do
      SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")
    end
  end

  test "stores wrapped content in source_text" do
    SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    assert @episode.source_text.include?("Test Title")
    assert @episode.source_text.include?("Article body.")
  end

  test "sets source_text_length to match source_text length" do
    SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    assert_equal @episode.source_text.length, @episode.source_text_length
  end

  test "includes free tier attribution for free users" do
    SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    assert @episode.source_text.include?("This audio was generated by PodRead")
  end

  test "excludes free tier attribution for premium users" do
    @episode.user.update!(account_type: :complimentary)

    SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    refute @episode.source_text.include?("This audio was generated by PodRead")
  end

  test "passes action_id to job" do
    Current.action_id = "test-action-456"

    assert_enqueued_with(job: GeneratesEpisodeAudioJob, args: [ { episode_id: @episode.id, action_id: "test-action-456" } ]) do
      SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")
    end
  ensure
    Current.action_id = nil
  end

  test "enqueues with priority 10 for free user" do
    @episode.user.update!(account_type: :standard)

    assert_enqueued_with(job: GeneratesEpisodeAudioJob, priority: 10) do
      SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")
    end
  end

  test "enqueues with priority 0 for premium user" do
    @episode.user.update!(account_type: :complimentary)

    assert_enqueued_with(job: GeneratesEpisodeAudioJob, priority: 0) do
      SubmitsEpisodeForProcessing.call(episode: @episode, content: "Article body.")
    end
  end
end
