# frozen_string_literal: true

require "test_helper"

class SubmitEpisodeForProcessingTest < ActiveSupport::TestCase
  setup do
    @episode = episodes(:one)
    @episode.update!(title: "Test Title", author: "Test Author")
    @episode.user.update!(account_type: :standard)

    Mocktail.replace(GenerateEpisodeAudio)
  end

  test "wraps content and calls GenerateEpisodeAudio" do
    stubs { |m| GenerateEpisodeAudio.call(episode: m.any) }.with { nil }

    SubmitEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    assert_equal 1, Mocktail.calls(GenerateEpisodeAudio, :call).size
  end

  test "stores wrapped content in source_text" do
    stubs { |m| GenerateEpisodeAudio.call(episode: m.any) }.with { nil }

    SubmitEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    assert @episode.source_text.include?("Test Title")
    assert @episode.source_text.include?("Article body.")
  end

  test "includes free tier attribution for free users" do
    stubs { |m| GenerateEpisodeAudio.call(episode: m.any) }.with { nil }

    SubmitEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    assert @episode.source_text.include?("This audio was generated by Very Normal TTS")
  end

  test "excludes free tier attribution for premium users" do
    @episode.user.update!(account_type: :complimentary)
    stubs { |m| GenerateEpisodeAudio.call(episode: m.any) }.with { nil }

    SubmitEpisodeForProcessing.call(episode: @episode, content: "Article body.")

    @episode.reload
    refute @episode.source_text.include?("This audio was generated by Very Normal TTS")
  end
end
