# frozen_string_literal: true

module Simulates
  module FetchesUrl
    include StructuredLogging

    SIMULATED_ARTICLE = <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <title>Simulated Article</title>
        <meta name="author" content="Simulation Mode">
      </head>
      <body>
        <article>
          <h1>Simulated Article for E2E Testing</h1>
          <p>This is a simulated article generated by PodRead's simulation mode.
          The actual URL was not fetched — instead, this placeholder content is returned
          to allow the full episode processing pipeline to run end-to-end without
          requiring external network access.</p>
          <p>Simulation mode mocks external services including URL fetching, text-to-speech
          synthesis, large language model processing, and cloud storage uploads. This enables
          realistic testing of the user interface, status transitions, ETA countdowns, and
          queue behavior without incurring API costs or requiring network connectivity.</p>
          <p>The content here is intentionally verbose to exceed the minimum character
          threshold required by the article extraction service. Each paragraph adds
          meaningful text that exercises the content processing pipeline, including
          character counting, content preview generation, and LLM-based summarization.</p>
          <p>PodRead converts articles into podcast episodes using a multi-step pipeline:
          first the article URL is fetched and its content extracted, then a large language
          model processes the text to generate a structured script, and finally a
          text-to-speech service synthesizes the audio. The resulting episode is stored in
          cloud storage and made available through the user's podcast feed.</p>
        </article>
      </body>
      </html>
    HTML

    def call
      log_info "simulation_url_fetch_started", url: url

      sleep(rand(0.5..1.5))

      log_info "simulation_url_fetch_completed", url: url, bytes: SIMULATED_ARTICLE.bytesize
      Result.success(SIMULATED_ARTICLE)
    end
  end
end
